project:
  output-dir: notebook_output
  type: website  
  
author: "Abdullah Mahmood"

format:
    html:
        toc: true
        toc-depth: 3
        html-math-method:
            method: mathjax
            url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
editor: source
jupyter: main